#!/bin/sh -efu

all_tasks="$(ls -F | grep '/$' | sed 's:/$::')"

tasks=

for i in $all_tasks; do
  script="./$i/create/run.sh"
  if test -x "$script"; then
    tasks=$(printf "%s\n%s" "$tasks" "$i")
  else
    printf "%10s: no run.sh\n" "$i"
  fi
done

printf "\n";

if test "${1:-x}" = "start"; then

  for task in $tasks; do
    printf "%10s:\n" "$task"
    dir="$task/create/"
    script="./$task/create/run.sh"

    (
      cd $dir;
      nohup ./run.sh >"log" 2>&1 </dev/null &
      echo $! >> ../../pids
    )
  done

elif test "${1:-x}" = "stop"; then

  pids=$(cat pids && true)
  echo killing $pids
  echo > pids

elif test "${1:-x}" = "list"; then

  echo not implemented 

else

  echo "What can I do for you? start? stop? list?"

fi
